spring:
  datasource:
    url: jdbc:h2:mem:${db_name:ratesAPIScrapper}
    driver-class-name: org.h2.Driver
    username: ${db_username:admin}
    password: ${db_passowrd:admin}
  jackson:
    date-format: yyyy-MM-dd
    time-zone: CET
external:
  rates:
    api:
      baseUrl: https://api.exchangeratesapi.io/v1
      accessKey: ${access_key:test}
      plan: free
feign:
  client:
    config:
      rates:
        connectionTimeout: 5000
        loggerLevel: ${log_level:full}
        decode404: false
